// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfabmvefj18PMSoV09t0e_lY8BNKtapzw',
    appId: '1:718563665129:web:c7c70d423aac680a76fc78',
    messagingSenderId: '718563665129',
    projectId: 'gmaps-spinoff',
    authDomain: 'gmaps-spinoff.firebaseapp.com',
    storageBucket: 'gmaps-spinoff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQKd3msNI7iZRARh2viQ2KLRD528kTEo',
    appId: '1:718563665129:android:f8b0234825a000e576fc78',
    messagingSenderId: '718563665129',
    projectId: 'gmaps-spinoff',
    storageBucket: 'gmaps-spinoff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKMkgmm1mo9TmbSLwx0KtVoeeexg3Ofc',
    appId: '1:718563665129:ios:c627299e955b606576fc78',
    messagingSenderId: '718563665129',
    projectId: 'gmaps-spinoff',
    storageBucket: 'gmaps-spinoff.appspot.com',
    iosBundleId: 'com.example.gmapsSpinoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKMkgmm1mo9TmbSLwx0KtVoeeexg3Ofc',
    appId: '1:718563665129:ios:86500aea709f32ea76fc78',
    messagingSenderId: '718563665129',
    projectId: 'gmaps-spinoff',
    storageBucket: 'gmaps-spinoff.appspot.com',
    iosBundleId: 'com.example.gmapsSpinoff.RunnerTests',
  );
}
